--
-- PostgreSQL database dump
--

-- Dumped from database version 11.0
-- Dumped by pg_dump version 11.0

-- Started on 2023-04-08 00:49:31

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2851 (class 1262 OID 630112)
-- Name: mydb; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE mydb WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'Portuguese_Brazil.1252' LC_CTYPE = 'Portuguese_Brazil.1252';


ALTER DATABASE mydb OWNER TO postgres;

\connect mydb

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: Eqnote
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO "Eqnote";

--
-- TOC entry 2852 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: Eqnote
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 199 (class 1259 OID 630140)
-- Name: category_products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category_products (
    id bigint NOT NULL,
    name text NOT NULL,
    imposto_id bigint
);


ALTER TABLE public.category_products OWNER TO postgres;

--
-- TOC entry 198 (class 1259 OID 630138)
-- Name: category_products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category_products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 197 (class 1259 OID 630115)
-- Name: groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.groups (
    id bigint NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.groups OWNER TO postgres;

--
-- TOC entry 196 (class 1259 OID 630113)
-- Name: groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 201 (class 1259 OID 630159)
-- Name: imposto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.imposto (
    id bigint NOT NULL,
    value double precision NOT NULL
);


ALTER TABLE public.imposto OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 630157)
-- Name: imposto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.imposto ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.imposto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 203 (class 1259 OID 630171)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    category_products_id bigint NOT NULL,
    groups_id bigint NOT NULL,
    description text,
    code bigint,
    value double precision,
    active boolean,
    img text
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 630169)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2841 (class 0 OID 630140)
-- Dependencies: 199
-- Data for Name: category_products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.category_products (id, name, imposto_id) FROM stdin;
3	Roupa	1
2	Eletro domestico	2
4	Perfumaria	3
1	Acessórios	4
\.


--
-- TOC entry 2839 (class 0 OID 630115)
-- Dependencies: 197
-- Data for Name: groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.groups (id, name) FROM stdin;
100	Preço Baixo
101	MixMatheus
102	Cacau Show
103	Brasil Cacau
1	Casas Bahia
2	ExtraFarma
3	Lider
5	Americanas
\.


--
-- TOC entry 2843 (class 0 OID 630159)
-- Dependencies: 201
-- Data for Name: imposto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.imposto (id, value) FROM stdin;
3	300
2	200
1	100
4	400
5	500
6	180
\.


--
-- TOC entry 2845 (class 0 OID 630171)
-- Dependencies: 203
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, category_products_id, groups_id, description, code, value, active, img) FROM stdin;
\.


--
-- TOC entry 2853 (class 0 OID 0)
-- Dependencies: 198
-- Name: category_products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.category_products_id_seq', 3, true);


--
-- TOC entry 2854 (class 0 OID 0)
-- Dependencies: 196
-- Name: groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.groups_id_seq', 103, true);


--
-- TOC entry 2855 (class 0 OID 0)
-- Dependencies: 200
-- Name: imposto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.imposto_id_seq', 6, true);


--
-- TOC entry 2856 (class 0 OID 0)
-- Dependencies: 202
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 1, false);


--
-- TOC entry 2709 (class 2606 OID 630147)
-- Name: category_products category_products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_products
    ADD CONSTRAINT category_products_pkey PRIMARY KEY (id);


--
-- TOC entry 2707 (class 2606 OID 630122)
-- Name: groups groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (id);


--
-- TOC entry 2711 (class 2606 OID 630163)
-- Name: imposto imposto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imposto
    ADD CONSTRAINT imposto_pkey PRIMARY KEY (id);


--
-- TOC entry 2713 (class 2606 OID 630175)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 2715 (class 2606 OID 630176)
-- Name: products category_products_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT category_products_id FOREIGN KEY (category_products_id) REFERENCES public.category_products(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 2716 (class 2606 OID 630184)
-- Name: products groups_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT groups_id FOREIGN KEY (groups_id) REFERENCES public.groups(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 2714 (class 2606 OID 630164)
-- Name: category_products imposto_category_products_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category_products
    ADD CONSTRAINT imposto_category_products_id FOREIGN KEY (imposto_id) REFERENCES public.imposto(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


-- Completed on 2023-04-08 00:49:32

--
-- PostgreSQL database dump complete
--

